# Generated by Django 5.1.2 on 2024-11-02 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcdata', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcinfo',
            old_name='description',
            new_name='other_info',
        ),
    ]
