# Generated by Django 5.1.2 on 2024-10-25 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pcData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcdata',
            old_name='data',
            new_name='cpu_json',
        ),
    ]
