# Generated by Django 5.1.2 on 2024-10-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcData', '0002_rename_data_pcdata_cpu_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcinfo',
            name='description',
            field=models.TextField(),
        ),
    ]
