# Generated by Django 5.1.2 on 2024-10-25 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcData', '0003_alter_pcinfo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pcinfo',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
