# Generated by Django 5.1.2 on 2024-10-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pcData', '0004_alter_pcinfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pcdata',
            name='gpu_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pcdata',
            name='memory_json',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
